name: Primeiro WorkFlow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Iniciar Gradle
        run: gradle init
      - name: Buildar com Gradle
        run: gradle build